name: theconstruct
favicon: null
layout_spectrum: 0.5848109170328826
typography_spectrum: 0.38320735143497586
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2664688597433269
  lightness: 0.20778205688111484
  saturation: 0.8187007280066609
  rhythmicContrast: 0.07291124248877168
purpose: []
